name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: src
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          path: src/main.pdf
          name: output
